In [17]:
# Import all necessary libraries.
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

In [19]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer(binary=True)

In [20]:
# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [21]:
# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())

[[0 1 1 0 0 1]]


In [22]:
# Instantiate a Bernoulli Naive Bayes model.
model = BernoulliNB(binarize=None)
# train the model using X_train_dtm
model.fit(x_train_dtm, y_train)
y_pred_class = model.predict(x_test_dtm)
print(y_pred_class)
print(model.predict_proba(x_test_dtm))

['not china']
[[0.19106679 0.80893321]]


In [23]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer()
# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [24]:
# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())
# Instantiate a Multinomial Naive Bayes model.
model = MultinomialNB()
# train the model using X_train_dtm
model.fit(x_train_dtm, y_train)

[[0 3 1 0 0 1]]


MultinomialNB()

In [25]:
y_pred_class = model.predict(x_test_dtm)
print(y_pred_class)
print(model.predict_proba(x_test_dtm))

['china']
[[0.68975861 0.31024139]]
